Some improvements
mosmeh/mochi pull request #2
Opened 2023-09-20 15:16 UTC by metaworm

* Codegen for `break` statement
* Debug information parsing, resolve line number and function name when error raises

2023-09-22 11:00 UTC, mosmeh commented on src/binary_chunk/deserialize.rs
> +    let mut abslineinfo = Vec::with_capacity(n as _);
Please use Rust style variable / function name, such as abs_line_info
Same for other parts. Do not just copy and paste names from the original Lua code.

2023-09-22 11:00 UTC, mosmeh commented on src/codegen.rs
> +
Please use same error messages as the original Lua.
For `NotInLoop`, its "break outside loop". So `BreakOutsideLoop`?

2023-09-22 11:00 UTC, mosmeh commented on src/codegen.rs
> +    pub continue_label: Option<Label>,
They don't have to be `pub`.
Also `continus_label` is unused.

2023-09-22 11:00 UTC, mosmeh commented on src/codegen.rs
> +struct LoopInfo {
Can't it be generic scopes / blocks rather than being specific to loops?

2023-09-22 11:00 UTC, mosmeh commented on src/codegen/ast.rs
> +            }
Please follow the style of other statements: `codegen_*_statement`

2023-09-22 11:00 UTC, mosmeh commented on src/runtime.rs
> +    fn last_lua_frame(&self) -> Option<&LuaFrame> {
current rather than last?

2023-09-22 11:00 UTC, mosmeh commented on src/runtime.rs
> +    fn stack_closure(&self, n: usize) -> Option<&'_ LuaClosure<'gc>> {
This function is only used in single place and doesn't look generally useful

2023-09-22 11:00 UTC, mosmeh commented on src/runtime/debug.rs
> +        let i = self.code.get(pc)?;
`i` sounds like a loop variable. `insn` is preferred

2023-09-22 11:00 UTC, mosmeh commented on src/runtime/debug.rs
> +    ) -> Option<(&'static str, &'a str)> {
It's not clear what the return value means. How about introducing a struct?

2023-09-22 11:00 UTC, mosmeh commented on src/runtime/debug.rs
> +        if name.filter(|&n| n == "_ENV").is_some() {
Can be replaced with pattern match?

2023-09-22 11:00 UTC, mosmeh commented on src/runtime/opcode.rs
> +    pub set_a: bool,
These names are too cryptic

2023-09-22 11:00 UTC, mosmeh commented on src/types/function.rs
> +pub struct LocalVar<'gc> {
Please use `LocalVariable` (if you want to make it Rusty) or `LocVar` (if you keep it C-ish)

2023-09-22 11:00 UTC, mosmeh commented on src/runtime/debug.rs
> +
Some of the functions don't have to be `pub`

2023-09-22 11:00 UTC, mosmeh commented on src/runtime/debug.rs
> +            // }
Unfinished?

2023-09-22 11:00 UTC, mosmeh commented on src/runtime/debug.rs
> +        None
Please return `?` with comments or `todo!()` here

2023-09-22 11:00 UTC, mosmeh commented on src/runtime/debug.rs
> +        // }
Hooks are not handled in other parts of mochi anyway...

2023-09-22 11:00 UTC, mosmeh commented on src/runtime.rs
> +                            "attempt to call a nil value ({kind}:{name:?})"
```suggestion
                            "attempt to call a nil value ({kind} {name:?})"
```

2023-09-22 11:04 UTC, mosmeh requested changes
I had a brief look at the code, but the review may be still incomplete.

Please fix rustc and clippy warnings.

2023-09-24 12:21 UTC, metaworm commented on src/runtime.rs
> +    fn last_lua_frame(&self) -> Option<&LuaFrame> {
I think "last" is more semantic.

2023-09-24 12:35 UTC, metaworm commented on src/runtime/debug.rs
> +            // }
Next commit will complete it

2023-09-24 12:41 UTC, metaworm commented on src/runtime/opcode.rs
> +    pub set_a: bool,
Mainly to correspond with the Lua source code, I can add comments to explain the meaning

2023-09-24 13:01 UTC, metaworm commented on src/runtime/debug.rs
> +    ) -> Option<(&'static str, &'a str)> {
Yes, struct is more clear.

2023-09-25 12:33 UTC, mosmeh commented
Not all points are fixed and there are clippy warnings. I will fix them by myself

2023-09-25 12:33 UTC, merged